apiVersion: v1
kind: Pod
metadata:
  name: a-nginx
  namespace: emphasis
  labels:
    app: nginx
    aVersion: { pod(b-nginx, metadata.resourceVersion) }
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
