apiVersion: v1
kind: Pod
metadata:
  name: b-nginx
  namespace: emphasis
  labels:
    app: nginx
    bUid: { pod(c-nginx, metadata.uid) }
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
